### ISSUE TITLE
Merge existing mpc control into simulation.

### ISSUE THREAD

**Issue by iacChris** [augcog/ROAR_Sim#3]
Since we have mpc control working on `decal` repo, we should also merge that into the current simulation repo.

**Comment by wuxiaohua1011** [comment]
Yes, did you already so that on the decal repo? Like submit and complete a pull request to master

**Comment by iacChris** [comment]
I have opened a pull request #4 to merge mpc control into master branch. In addition, branch [mpc_control](https://github.com/augcog/ROAR-Sim/tree/mpc_control) can be safely deleted since it only contains the legacy code for now.

**Comment by wuxiaohua1011** [comment]
pull request #4 has been merged. Can you delete the mpc_control branch on the ROAR_DeCal repo. 

mucho gracias~~
